language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script: composer install --prefer-source --no-interaction

script: vendor/bin/phpspec --config=phpspec.yml run

after_script: vendor/bin/codacycoverage clover build/coverage.xml