language: php

php:
  - 7.0

before_install:
- sudo apt-get update
- sudo apt-get install make build-essential automake php5-dev php-pear
- git clone git://github.com/jedisct1/libsodium.git
- cd libsodium
- git checkout 1.0.10
- ./autogen.sh
- ./configure && make check
- sudo make install
- cd ..
- pecl install libsodium

before_script: composer install --prefer-source --no-interaction

script: vendor/bin/phpspec --config=phpspec.yml run

after_script: vendor/bin/codacycoverage clover build/coverage.xml